### PR TITLE
Add version to tag message schema

### PR DESCRIPTION
**Pull request by wittjosiah**

### CODE REVIEW

**Comment by mixmix** [comment]
looks good to me !

**Comment by mixmix** [comment]
in your index.js you need to make sure you export `sync/isTag` so people can use the schema!

**Comment by mixmix** [comment]
let me know if you want / need a more in depth review of this module.
At a high level glance looks like you've got your code in places that are familiar, and you've got a clear API and if you want to mess with the details later you can!

**Comment by wittjosiah** [comment]
@mixmix I would happily accept a gift of code review at some point. I don't think a lot has changed since you last reviewed scuttle-tag, but I'm not sure how in depth you were at the time.

**Pull request merged**
